<?php
$this->table='doc_list';
$this->x_column_list_arr=
[
    'order_num'=>['name'=>'순번','type'=>'int','length'=>'','width'=>'100','pri'=>''],
    'sort1'=>['name'=>'구분1','type'=>'int','length'=>'','width'=>'100','pri'=>''],
    'sort2'=>['name'=>'구분2','type'=>'int','length'=>'','width'=>'100','pri'=>''],
];
$this->x_pri_col_arr=['id'];
$this->x_basic_col_arr=['order_num','sort1','sort2','sort3','created_date','update_date'];
